spring:
  application:
    name: eureka-server
#  security:
#    user:
#      name: "admin"
#      password: "admin123"
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    # 允许自己注册到注册中心上
    register-with-eureka: true
    # 是否允许拉取别的注册中心的信息
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 开启自我保护
    enable-self-preservation: true
logging:
  level:
    # 不打印 spring 的 CONDITIONS EVALUATION REPORT 的日志的输出
    org.springframework.boot.autoconfigure: ERROR
    # 不打印 eureka 的心跳日志的输出
    com.netflix.eureka: ERROR
    ROOT: info